# For running directly from the source directory, set this to "public" or omit it.
public_dir = "/usr/share/dancelist"

# The file, directory or URL from which to read events data. This will probably be from the
# dancelist-data repository.
events = "https://raw.githubusercontent.com/qwandor/dancelist-data/release/events.yaml"

# The address on which the server should listen.
bind_address = "0.0.0.0:3002"

# A secret token used to force a reload of event data.
reload_token = "secret"
